import pyautogui, time

def bury():
    # column 1
    pyautogui.moveTo(1473,755)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1473,793)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1473,832)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1473,865)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1473,905)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1473,939)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1473,975)
    pyautogui.click()
    time.sleep(1)

    # column 2
    pyautogui.moveTo(1517,755)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1517,793)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1517,832)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1517,865)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1517,905)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1517,939)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1517,975)
    pyautogui.click()
    time.sleep(1)

    # column 3
    pyautogui.moveTo(1562,755)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1562,793)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1562,832)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1562,865)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1562,905)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1562,939)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1562,975)
    pyautogui.click()
    time.sleep(1)

    # column 4
    pyautogui.moveTo(1601,755)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1601,793)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1601,832)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1601,865)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1601,905)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1601,939)
    pyautogui.click()
    time.sleep(1)
    pyautogui.moveTo(1601,975)
    pyautogui.click()
    time.sleep(1)
    disc = pyautogui.locateOnScreen('disconnected.png',confidence=.7)
    if disc:
        exit()

num=49
for i in range(num//28):
    # click bank
    pyautogui.moveTo(811, 785)
    pyautogui.click()
    time.sleep(1)

    # select all
    pyautogui.moveTo(788, 829)
    pyautogui.click()

    # click bones
    pyautogui.moveTo(537, 422)
    pyautogui.click()
    time.sleep(1)

    # press esc
    pyautogui.press('esc')
    print(i+1," of ",num//28)
    bury()
 